import React,{useState} from 'react';
import {Eye,EyeOff,Mail,Lock,UserRound,ArrowRight,ShieldCheck,Warehouse,ChartNoAxesCombined} from 'lucide-react';
import Logo from '../components/Logo';
import {isSupabaseConfigured,supabase} from '../lib/supabase';

export default function Auth({mode,setMode,onLogin,recoveryMode=false}:{mode:'login'|'signup'|'forgot';setMode:(m:any)=>void;onLogin:()=>void;recoveryMode?:boolean}){
 const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [confirm,setConfirm]=useState('');
 const submitLogin=async()=>{setMessage(''); if(!email||!password){setMessage('Enter your email and password.');return} if(!supabase||!isSupabaseConfigured){setMessage('Supabase is not configured in this deployment. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY, then redeploy.');return} setBusy(true); const {error}=await supabase.auth.signInWithPassword({email,password}); setBusy(false); if(error){setMessage(error.message);return} onLogin()};
 const submitSignup=async()=>{setMessage(''); if(!name.trim()||!email||!password||password!==confirm){setMessage('Complete all fields and make sure passwords match.');return} if(password.length<8){setMessage('Password must be at least 8 characters.');return} if(!supabase||!isSupabaseConfigured){setMessage('Supabase is not configured in this deployment. Add the VITE_SUPABASE variables and redeploy.');return} setBusy(true); const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name.trim()}}}); setBusy(false); if(error){setMessage(error.message);return} if(data.session) onLogin(); else setMessage('Account created. Check your email to confirm the account, then log in.');};
 const sendReset=async()=>{setMessage(''); if(!email){setMessage('Enter your account email.');return} if(!supabase||!isSupabaseConfigured){setMessage('Supabase is not configured in this deployment.');return} setBusy(true); const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin}); setBusy(false); if(error){setMessage(error.message);return} setMessage('Password reset email sent. Open the secure link in your email to choose a new password.');};
 const updatePassword=async()=>{setMessage(''); if(password.length<8){setMessage('Password must be at least 8 characters.');return} if(password!==confirm){setMessage('Passwords do not match.');return} if(!supabase){setMessage('Supabase is not configured.');return} setBusy(true); const {error}=await supabase.auth.updateUser({password}); setBusy(false); if(error){setMessage(error.message);return} setMessage('Password updated successfully. You can continue to StockSense.'); onLogin()};
 const forgotRecovery=recoveryMode;
 return <div className="auth-page"><div className="auth-visual"><Logo/><div className="auth-copy"><p className="eyebrow">INVENTORY MANAGEMENT REIMAGINED</p><h1>Control Your Stock.<br/><span>Smarter.</span></h1><p>Real-time tracking, seamless warehouse operations and complete control — all in one place.</p><div className="feature-list"><div><ShieldCheck/><span><b>Real-time Tracking</b><small>Every authenticated team member sees the shared live inventory.</small></span></div><div><Warehouse/><span><b>Multi-Warehouse Support</b><small>Manage multiple locations.</small></span></div><div><ChartNoAxesCombined/><span><b>Smart Insights</b><small>Charts calculated from your live data.</small></span></div></div></div><div className="auth-orb one"></div><div className="auth-orb two"></div></div><div className="auth-panel"><div className="auth-card">
    {mode==='login'&&<><h2>Welcome Back</h2><p>Login to your StockSense account</p><Field icon={<Mail/>} placeholder="Email address" value={email} onChange={setEmail}/><Field icon={<Lock/>} placeholder="Password" type={show?'text':'password'} value={password} onChange={setPassword} right={<button onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button>}/><div className="auth-row"><label><input type="checkbox"/> Remember me</label><button className="link" onClick={()=>{setMode('forgot');setMessage('')}}>Forgot Password?</button></div><button className="gradient-btn" onClick={submitLogin} disabled={busy}>{busy?'Signing in…':'Login'} <ArrowRight/></button><p className="switch">New to StockSense? <button onClick={()=>setMode('signup')}>Create an account</button></p></>}
    {mode==='signup'&&<><h2>Create Your Account</h2><p>Fill in your details to get started</p><Field icon={<UserRound/>} placeholder="Full Name" value={name} onChange={setName}/><Field icon={<Mail/>} placeholder="Email address" value={email} onChange={setEmail}/><Field icon={<Lock/>} placeholder="Password (8+ characters)" type="password" value={password} onChange={setPassword}/><Field icon={<Lock/>} placeholder="Confirm Password" type="password" value={confirm} onChange={setConfirm}/><label className="terms"><input type="checkbox"/> I agree to the <u>Terms of Service</u> and <u>Privacy Policy</u></label><button className="gradient-btn" onClick={submitSignup} disabled={busy}>{busy?'Creating…':'Create Account'} <ArrowRight/></button><p className="switch">Already have an account? <button onClick={()=>setMode('login')}>Login</button></p></>}
    {mode==='forgot'&&<>{forgotRecovery?<><h2>Set New Password</h2><p>Choose a new secure password for your StockSense account.</p><Field icon={<Lock/>} placeholder="New password (8+ characters)" type="password" value={password} onChange={setPassword}/><Field icon={<Lock/>} placeholder="Confirm new password" type="password" value={confirm} onChange={setConfirm}/><button className="gradient-btn" onClick={updatePassword} disabled={busy}>{busy?'Updating…':'Update Password'} <ArrowRight/></button></>:<><h2>Reset Your Password</h2><p>We will email a secure password-reset link to your account.</p><Field icon={<Mail/>} placeholder="Email address" value={email} onChange={setEmail}/><button className="gradient-btn" onClick={sendReset} disabled={busy}>{busy?'Sending…':'Send Reset Email'} <ArrowRight/></button></>}<p className="switch"><button onClick={()=>setMode('login')}>← Back to Login</button></p></>}
    {message&&<div className="auth-message">{message}</div>}
  </div></div></div>
}
function Field({icon,placeholder,type='text',right,value,onChange}:{icon:React.ReactNode;placeholder:string;type?:string;right?:React.ReactNode;value?:string;onChange?:(v:string)=>void}){return <div className="field">{icon}<input type={type} placeholder={placeholder} value={value} onChange={e=>onChange?.(e.target.value)}/>{right}</div>}
