import React, {useState} from 'react';
import {Eye,EyeOff,Mail,Lock,UserRound,ArrowRight,ShieldCheck,Warehouse,ChartNoAxesCombined} from 'lucide-react';
import Logo from '../components/Logo';
import {isSupabaseConfigured, supabase} from '../lib/supabase';

export default function Auth({mode,setMode,onLogin}:{mode:'login'|'signup'|'forgot';setMode:(m:any)=>void;onLogin:()=>void}){
  const [show,setShow]=useState(false); const [step,setStep]=useState(1); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [confirm,setConfirm]=useState('');
  const submitLogin=async()=>{setMessage(''); if(!email||!password){setMessage('Enter your email and password.');return} if(!isSupabaseConfigured){onLogin();return} setBusy(true); const {error}=await supabase!.auth.signInWithPassword({email,password}); setBusy(false); if(error){setMessage(error.message);return} onLogin()};
  const submitSignup=async()=>{setMessage(''); if(!name||!email||!password||password!==confirm){setMessage('Complete all fields and make sure passwords match.');return} if(!isSupabaseConfigured){onLogin();return} setBusy(true); const {data,error}=await supabase!.auth.signUp({email,password,options:{data:{full_name:name}}}); setBusy(false); if(error){setMessage(error.message);return} if(data.session) onLogin(); else setMessage('Account created. Check your email to confirm the account, then log in.');};
  const resetPassword=async()=>{setMessage(''); if(!email){setMessage('Enter your account email.');return} if(!isSupabaseConfigured){setStep(2);return} setBusy(true); const {error}=await supabase!.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin}); setBusy(false); if(error){setMessage(error.message);return} setMessage('Password reset instructions have been sent to your email.');};
  const google=async()=>{if(!isSupabaseConfigured){onLogin();return} setBusy(true); const {error}=await supabase!.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}}); setBusy(false); if(error)setMessage(error.message)};
  return <div className="auth-page"><div className="auth-visual"><Logo/><div className="auth-copy"><p className="eyebrow">INVENTORY MANAGEMENT REIMAGINED</p><h1>Control Your Stock.<br/><span>Smarter.</span></h1><p>Real-time tracking, seamless warehouse operations and complete control — all in one place.</p><div className="feature-list"><div><ShieldCheck/><span><b>Real-time Tracking</b><small>Every connected user sees live changes.</small></span></div><div><Warehouse/><span><b>Multi-Warehouse Support</b><small>Manage multiple locations.</small></span></div><div><ChartNoAxesCombined/><span><b>Smart Insights</b><small>Charts calculated from live data.</small></span></div></div></div><div className="auth-orb one"></div><div className="auth-orb two"></div></div><div className="auth-panel"><div className="auth-card">
    {mode==='login'&&<><h2>Welcome Back</h2><p>Login to your StockSense account</p><Field icon={<Mail/>} placeholder="Email address" value={email} onChange={setEmail}/><Field icon={<Lock/>} placeholder="Password" type={show?'text':'password'} value={password} onChange={setPassword} right={<button onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button>}/><div className="auth-row"><label><input type="checkbox"/> Remember me</label><button className="link" onClick={()=>setMode('forgot')}>Forgot Password?</button></div><button className="gradient-btn" onClick={submitLogin} disabled={busy}>{busy?'Signing in…':'Login'} <ArrowRight/></button><div className="or"><span/>OR<span/></div><button className="google" onClick={google} disabled={busy}>G <span>Continue with Google</span></button><p className="switch">New to StockSense? <button onClick={()=>setMode('signup')}>Create an account</button></p></>}
    {mode==='signup'&&<><h2>Create Your Account</h2><p>Fill in your details to get started</p><Field icon={<UserRound/>} placeholder="Full Name" value={name} onChange={setName}/><Field icon={<Mail/>} placeholder="Email address" value={email} onChange={setEmail}/><Field icon={<Lock/>} placeholder="Password" type="password" value={password} onChange={setPassword}/><Field icon={<Lock/>} placeholder="Confirm Password" type="password" value={confirm} onChange={setConfirm}/><label className="terms"><input type="checkbox"/> I agree to the <u>Terms of Service</u> and <u>Privacy Policy</u></label><button className="gradient-btn" onClick={submitSignup} disabled={busy}>{busy?'Creating…':'Create Account'} <ArrowRight/></button><div className="or"><span/>OR<span/></div><button className="google" onClick={google}>G <span>Continue with Google</span></button><p className="switch">Already have an account? <button onClick={()=>setMode('login')}>Login</button></p></>}
    {mode==='forgot'&&<><h2>{isSupabaseConfigured?'Reset Your Password':step===1?'Reset Your Password':step===2?'Verify OTP':'Set New Password'}</h2><p>{isSupabaseConfigured?'We will email secure password-reset instructions.':step===1?'Follow the steps to securely reset your StockSense account.':step===2?'Enter the demo verification code below.':'Create a new secure password.'}</p>{isSupabaseConfigured?<><Field icon={<Mail/>} placeholder="Email address" value={email} onChange={setEmail}/><button className="gradient-btn" onClick={resetPassword} disabled={busy}>{busy?'Sending…':'Send Reset Email'} <ArrowRight/></button></>:<>{step===1&&<><Field icon={<Mail/>} placeholder="Email address" value={email} onChange={setEmail}/><button className="gradient-btn" onClick={()=>setStep(2)}>Send OTP <ArrowRight/></button></>}{step===2&&<><Field icon={<Lock/>} placeholder="Demo OTP: 123456"/><button className="gradient-btn" onClick={()=>setStep(3)}>Verify OTP <ArrowRight/></button></>}{step===3&&<><Field icon={<Lock/>} placeholder="New password" type="password"/><Field icon={<Lock/>} placeholder="Confirm password" type="password"/><button className="gradient-btn" onClick={()=>setMode('login')}>Reset Password <ArrowRight/></button></>}</>}<p className="switch"><button onClick={()=>setMode('login')}>← Back to Login</button></p></>}
    {message&&<div className="auth-message">{message}</div>}
  </div></div></div>
}
function Field({icon,placeholder,type='text',right,value,onChange}:{icon:React.ReactNode;placeholder:string;type?:string;right?:React.ReactNode;value?:string;onChange?:(v:string)=>void}){return <div className="field">{icon}<input type={type} placeholder={placeholder} value={value} onChange={e=>onChange?.(e.target.value)}/>{right}</div>}
