import React,{useMemo} from 'react';import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,PieChart,Pie,Cell} from 'recharts';import {AppState} from '../lib/types';import KpiCard from '../components/KpiCard';import {Package,AlertTriangle} from 'lucide-react';
const colors=['#1687ff','#7b3cff','#e82bd0','#f44372','#27d9b5','#ff9f43'];
function dayKey(d:Date){return d.toISOString().slice(0,10)}
function pctChange(current:number,previous:number){if(previous===0)return current>0?'+100%':'0%';const p=Math.round(((current-previous)/previous)*100);return `${p>=0?'+':''}${p}%`}
export default function Dashboard({state,setPage}:{state:AppState;setPage:(p:string)=>void}){
 const totals=useMemo(()=>state.products.map(p=>({...p,total:state.inventory.filter(i=>i.productId===p.id).reduce((a,b)=>a+b.quantity,0)})),[state]);
 const total=totals.reduce((a,b)=>a+b.total,0),low=totals.filter(p=>p.total>0&&p.total<=p.reorder).length,out=totals.filter(p=>p.total===0).length;
 const pendingR=state.receipts.filter(r=>!['Done','Canceled'].includes(r.status)).length,pendingD=state.deliveries.filter(r=>!['Done','Canceled'].includes(r.status)).length,pendingT=state.transfers.filter(r=>!['Done','Canceled'].includes(r.status)).length;
 const now=new Date(); const currentStart=new Date(now);currentStart.setDate(now.getDate()-6); const prevStart=new Date(now);prevStart.setDate(now.getDate()-13); const prevEnd=new Date(now);prevEnd.setDate(now.getDate()-7);
 const operationCount=(start:Date,end:Date)=>state.ledger.filter(l=>{const d=new Date(l.timestamp);return d>=start&&d<=end}).length;
 const currOps=operationCount(currentStart,now),prevOps=operationCount(prevStart,prevEnd); const liveDelta=pctChange(currOps,prevOps);
 const movement=useMemo(()=>{const rows=[];for(let i=13;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=dayKey(d);const vals={d:d.toLocaleDateString('en-IN',{day:'2-digit',month:'short'}),r:0,del:0,adj:0,tr:0};state.ledger.filter(l=>dayKey(new Date(l.timestamp))===key).forEach(l=>{if(l.operation==='Receipt')vals.r+=Math.abs(l.quantity);else if(l.operation==='Delivery')vals.del+=Math.abs(l.quantity);else if(l.operation==='Adjustment')vals.adj+=Math.abs(l.quantity);else vals.tr+=Math.abs(l.quantity)});rows.push(vals)}return rows},[state]);
 const cats=Object.entries(totals.reduce((a,p)=>{a[p.category]=(a[p.category]||0)+p.total;return a},{} as Record<string,number>)).map(([name,value])=>({name,value}));
 const greeting=new Date().getHours()<12?'Good morning':new Date().getHours()<18?'Good afternoon':'Good evening';
 return <><div className="welcome"><div><h1>{greeting}, Aethernyx! <span>👋</span></h1><p>Live inventory state, operational activity and stock alerts.</p></div><button className="tip">Live system · {currOps} ledger events in the last 7 days</button></div>
 <div className="kpi-grid"><KpiCard type="total" title="Total Products in Stock" value={total} delta={liveDelta} onClick={()=>setPage('stock')}/><KpiCard type="low" title="Low Stock Items" value={low} onClick={()=>setPage('stock')}/><KpiCard type="out" title="Out of Stock Items" value={out} onClick={()=>setPage('stock')}/><KpiCard type="receipt" title="Pending Receipts" value={pendingR} onClick={()=>setPage('receipts')}/><KpiCard type="delivery" title="Pending Deliveries" value={pendingD} onClick={()=>setPage('deliveries')}/><KpiCard type="transfer" title="Internal Transfers Scheduled" value={pendingT} onClick={()=>setPage('transfers')}/></div>
 <div className="dash-grid"><section className="panel chart-panel"><div className="panel-head"><div><h3>Inventory Movement</h3><small>Derived directly from the live stock ledger · last 14 days</small></div><span className="live-dot">● LIVE</span></div><ResponsiveContainer width="100%" height={220}><BarChart data={movement}><XAxis dataKey="d" stroke="#66738c"/><YAxis stroke="#66738c"/><Tooltip contentStyle={{background:'#07101f',border:'1px solid #243553'}}/><Bar dataKey="r" name="Receipts" fill="#27b9ff" radius={[4,4,0,0]}/><Bar dataKey="del" name="Deliveries" fill="#ff287e" radius={[4,4,0,0]}/><Bar dataKey="adj" name="Adjustments" fill="#8b39ff" radius={[4,4,0,0]}/><Bar dataKey="tr" name="Transfers" fill="#ff9f43" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></section>
 <section className="panel"><div className="panel-head"><div><h3>Stock by Category</h3><small>Calculated from current inventory records</small></div><button className="view" onClick={()=>setPage('products')}>View All</button></div><div className="donut"><ResponsiveContainer width="48%" height={190}><PieChart><Pie data={cats} dataKey="value" nameKey="name" innerRadius={55} outerRadius={82} paddingAngle={3}>{cats.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{background:'#07101f',border:'1px solid #243553'}}/></PieChart></ResponsiveContainer><div className="cat-list">{cats.map((c,i)=><div key={c.name}><i style={{background:colors[i%colors.length]}}/><span>{c.name}</span><b>{Math.round(c.value/Math.max(total,1)*100)}%</b></div>)}</div></div></section>
 <section className="panel alerts"><div className="panel-head"><h3>Low Stock Alerts</h3><button className="view" onClick={()=>setPage('stock')}>View All</button></div>{totals.filter(p=>p.total<=p.reorder).slice(0,5).map(p=><div className="alert-row" key={p.id}><div className="alert-icon"><AlertTriangle size={16}/></div><div><b>{p.name}</b><small>SKU: {p.sku} · reorder at {p.reorder}</small></div><strong>{p.total} left</strong></div>)}{!totals.some(p=>p.total<=p.reorder)&&<div className="empty-mini">All products are above reorder level.</div>}</section></div>
 <section className="panel recent"><div className="panel-head"><div><h3>Recent Operations</h3><small>Live stock ledger · newest events first</small></div><button className="view" onClick={()=>setPage('history')}>View All</button></div><div className="activity-list">{state.ledger.slice(0,8).map(l=><div className="activity" key={l.id}><div className={'activity-icon '+l.operation.toLowerCase().replaceAll(' ','-')}><Package size={15}/></div><div><b>{l.operation}</b><small>{l.reference} · {l.source} → {l.destination} · {new Date(l.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div><strong className={l.quantity>=0?'plus':'minus'}>{l.quantity>=0?'+':''}{l.quantity}</strong><span className={'status '+l.status.toLowerCase()}>{l.status}</span></div>)}</div></section></>}
