import React,{useEffect,useRef,useState} from 'react';
import {load,save,reset} from './lib/store';
import {AppState} from './lib/types';
import Sidebar from './components/Sidebar'; import Topbar from './components/Topbar'; import Toast from './components/Toast'; import Dashboard from './pages/Dashboard';
import {Products,Stock,Receipts,Deliveries,Transfers,Adjustments,History,Warehouses,Locations,Profile} from './pages/Pages'; import Auth from './pages/Auth';
import {fetchCloudState,pushCloudState,subscribeToCloudState} from './lib/cloudStore'; import {isSupabaseConfigured,supabase} from './lib/supabase';

export default function App(){
 const [authed,setAuthed]=useState(()=>localStorage.getItem('stocksense_auth')==='1'); const [authMode,setAuthMode]=useState<'login'|'signup'|'forgot'>('login');
 const [page,setPage]=useState('dashboard'); const [state,setState]=useState<AppState>(()=>load()); const [toast,setToast]=useState(''); const [loading,setLoading]=useState(isSupabaseConfigured);
 const [userId,setUserId]=useState<string|null>(null); const [cloudReady,setCloudReady]=useState(!isSupabaseConfigured); const skipNextCloudPush=useRef(false);
 useEffect(()=>{ if(!supabase){setLoading(false);return} let mounted=true; supabase.auth.getSession().then(({data})=>{if(!mounted)return;setUserId(data.session?.user.id??null);setAuthed(Boolean(data.session));setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setUserId(session?.user.id??null);setAuthed(Boolean(session)); if(session)localStorage.setItem('stocksense_auth','1'); else localStorage.removeItem('stocksense_auth')}); return()=>{mounted=false;subscription.unsubscribe()}; },[]);
 useEffect(()=>{ if(!authed||!isSupabaseConfigured)return; let cancelled=false; (async()=>{try{const remote=await fetchCloudState();if(remote&&!cancelled){skipNextCloudPush.current=true;setState(remote);}else if(!remote)await pushCloudState(state,userId); if(!cancelled)setCloudReady(true)}catch(e){console.error(e);setToast('Cloud sync unavailable. Working locally until it reconnects.'); if(!cancelled)setCloudReady(true)}})(); const stop=subscribeToCloudState(next=>{if(!cancelled){skipNextCloudPush.current=true;setState(next)}},()=>setToast('Realtime connection interrupted. Retrying with Supabase…')); return()=>{cancelled=true;stop()};},[authed]);
 useEffect(()=>{save(state); if(skipNextCloudPush.current){skipNextCloudPush.current=false;return} if(authed&&isSupabaseConfigured&&cloudReady){const t=setTimeout(()=>pushCloudState(state,userId).catch(()=>setToast('Could not sync the latest change to Supabase.')),250);return()=>clearTimeout(t)}},[state,authed,userId,cloudReady]);
 const login=()=>{localStorage.setItem('stocksense_auth','1');setAuthed(true);setToast(isSupabaseConfigured?'Connected to StockSense realtime cloud.':'Welcome to StockSense local demo.');};
 const logout=async()=>{if(supabase)await supabase.auth.signOut();localStorage.removeItem('stocksense_auth');setAuthed(false);setAuthMode('login')}; const go=(p:string)=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})};
 if(loading)return <div className="loading-screen"><div className="loader"></div><h2>Connecting to StockSense…</h2><p>Loading your live inventory workspace.</p></div>;
 if(!authed)return <Auth mode={authMode} setMode={setAuthMode} onLogin={login}/>;
 return <div className="app-shell"><Sidebar page={page} setPage={go} onLogout={logout}/><main className="main"><Topbar state={state} onNavigate={go}/>{page==='dashboard'&&<Dashboard state={state} setPage={go}/>} {page==='products'&&<Products state={state} setState={setState}/>} {page==='stock'&&<Stock state={state}/>} {page==='receipts'&&<Receipts state={state} setState={s=>{setState(s);setToast('Receipt operation completed and synced live.')}}/>} {page==='deliveries'&&<Deliveries state={state} setState={s=>{setState(s);setToast('Delivery validated and synced live.')}}/>} {page==='transfers'&&<Transfers state={state} setState={s=>{setState(s);setToast('Transfer completed and synced live.')}}/>} {page==='adjustments'&&<Adjustments state={state} setState={s=>{setState(s);setToast('Adjustment applied and synced live.')}}/>} {page==='history'&&<History state={state}/>} {page==='warehouses'&&<Warehouses state={state} setState={setState}/>} {page==='locations'&&<Locations state={state} setState={setState}/>} {page==='profile'&&<Profile/>}{toast&&<Toast msg={toast} onClose={()=>setToast('')}/>}<button className="reset-demo" onClick={reset}>Reset local demo data</button></main></div>
}
